"""empty message

Revision ID: 49511bbcf0db
Revises: 4a76d203630b
Create Date: 2019-11-09 14:47:36.975881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49511bbcf0db'
down_revision = '4a76d203630b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'password')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
